#----------------------------------------------------------------
# Server Configuration
#----------------------------------------------------------------
server
  port: 8080

# postgresql datasource
spring:
  sql.init:
    mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: accountingUser
    password: accountingPassword
    initialization-mode: never
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Log slow queries
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
        # Generate and log statistics
        generate_statistics: false
        default_schema: accounting
  flyway:
    enabled: true
    user: accountingUser
    password: accountingPassword
    schemas: accounting
    locations: classpath:db/migrations,classpath:/db/testdata
# logging level
logging:
  level:
    root: INFO
    web: DEBUG
    graphql: DEBUG
    org.springframework.graphql: DEBUG
    # Generate and log statistics
    org.hibernate.stat: DEBUG
    # Log all SQL statements
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    # Log cache operations
    org.hibernate.cache: DEBUG


# GraphQL Settings
graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true
  graphiql:
    mapping: /graphiql
    endpoint:
      graphql: /graphql
      subscriptions: /subscriptions
    subscriptions:
      timeout: 30
      reconnect: false
    basePath: /
    enabled: true
    pageTitle: GraphiQL
    cdn:
      enabled: false
      version: latest
    props:
      resources:
        query: query.graphql
        defaultQuery: defaultQuery.graphql
        variables: variables.json
      variables:
        editorTheme: "solarized light"