version: "3"

services:
  api-service:
    image: accounting-backend
    container_name: accounting-backend
    build:
      context: accounting-backend/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=gitpod
      - SPRING_DATASOURCE_PASSWORD=gitpod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=gitpod
      - POSTGRES_PASSWORD=gitpod
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
