create TABLE customers (
  id UUID NOT NULL,
   name VARCHAR(255),
   address VARCHAR(255),
   city VARCHAR(255),
   phone VARCHAR(255),
   CONSTRAINT pk_customers PRIMARY KEY (id)
);

create TABLE companies (
  id UUID NOT NULL,
   name VARCHAR(255),
   address VARCHAR(255),
   city VARCHAR(255),
   phone VARCHAR(255),
   customer_id UUID NOT NULL,
   CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies ADD CONSTRAINT fk_companies_customers FOREIGN KEY (customer_id) REFERENCES customers (id);


create TABLE transactions (
   id UUID NOT NULL,
   name VARCHAR(255),
   number INTEGER,
   transaction_date DATE,
   amount DECIMAL,
   type VARCHAR(255),
   company_id UUID NOT NULL,
   CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions ADD CONSTRAINT fk_transactions_companies FOREIGN KEY (company_id) REFERENCES companies (id);

create TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   role VARCHAR(255),
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

create TABLE users (
  username VARCHAR(255) NOT NULL,
   password VARCHAR(255),
   enabled BOOLEAN,
   fullname VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (username)
);

alter table roles add CONSTRAINT uc_b650b56de77e2f2022f4b0970 UNIQUE (username, role);

alter table roles add CONSTRAINT FK_ROLES_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);